name: Build Ultimate Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: 
          node-version: '22' # Version 20 se badal kar 22 kar diya hai
          cache: 'yarn'
          
      - uses: actions/setup-java@v4
        with: { distribution: 'zulu', java-version: '17' }
        
      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          
      - name: Setup Capacitor
        run: |
          yarn add @capacitor/core @capacitor/cli @capacitor/android
          npx cap init "SuperApp" "com.super.app" --web-dir=out
          npx cap add android
          npx cap sync android
          
      - name: Compile APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - uses: actions/upload-artifact@v4
        with:
          name: my-perfect-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
